### ISSUE TITLE
Design changes from Korie

### ISSUE THREAD

**Issue by zachfox** [GottBott/CraigD#6]
* In logo, "DISABLED CLIMBER MOTIVATIONAL SPEAKER is off-center (to the right). Maybe all text in this logo is right aligned. 
* on big monitor, korie says that the "About Craig" thing is too wide cuz it just scales as wide as the screen. 
* on big monitor photo gallery isn't centered (margin on the right.

**Comment by GottBott** [comment]
good catch on the large screen
